| grantee       | column_name | privilege_type |
| ------------- | ----------- | -------------- |
| anon          | seviye      | INSERT         |
| anon          | seviye      | REFERENCES     |
| anon          | seviye      | SELECT         |
| anon          | seviye      | UPDATE         |
| anon          | xp          | INSERT         |
| anon          | xp          | REFERENCES     |
| anon          | xp          | SELECT         |
| anon          | xp          | UPDATE         |
| authenticated | seviye      | INSERT         |
| authenticated | seviye      | REFERENCES     |
| authenticated | seviye      | SELECT         |
| authenticated | seviye      | UPDATE         |
| authenticated | xp          | INSERT         |
| authenticated | xp          | REFERENCES     |
| authenticated | xp          | SELECT         |
| authenticated | xp          | UPDATE         |